# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types:
      - reopened
      - opened
      
  pull_request:
    types:
      - opened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::830303460469:role/GithubActionsSQSRole-dev-vvvallab-us-east-1
          aws-region: us-east-1
     # - name: Dump GitHub context
       # env:
        #   GITHUB_CONTEXT: ${{ toJson(github) }}
        #run: |
           #aws sqs send-message --queue-url https://sqs.us-west-2.amazonaws.com/830303460469/githubtest --message-body " ${{ github.event.issue.title }} ${{ github.event.issue.body }}" --delay-seconds 1 
      
      - uses: varunvallabhan52/sqs-action@v1.0
        with:
          sqs-url: https://sqs.us-east-1.amazonaws.com/830303460469/TicketingStack-dev-vvvallab-us-ea-GithubSimTicketingSQSdevvvvallabu-SKcRXqGbwDYc
          message: ${{ toJSON(github) }}
      
      - name: Fetch events
        env:
          ID: ${{ github.event.id }}
          title: ${{ github.event.issue.title }}
          DATE: ${{ github.event.issue.created_at }}
          #body: ${{ github.event.issue.body }}
        run: |